package variable;

public final class Constants {
	public static final String EXISTS_DB = "select 1 from %s where %s = ?";
	public static final String ADD_DB = "call add";
	public static final String GET_DEDUCTIONS = "select * from employeeDeduction where employeeNumber = ?";
	public static final String UPDATE_DEDUCTIONS = "call updateEmployeeDeduction (?, ?, ?, ?, ?, ?)";
	public static final double MINIMUM_SALARY = 1500.00;
	//public static final int SHEET_INDEX = 0;
	//public static final int ROW_INDEX = 1;
	//public static final int COLUMN_INDEX = 2;
	
	public static final Object[] HEADERS = {
		"empno",
		"name",
		"rate",
		"days",
		"basic",
		"cola",
		"tcola",
		"sea",
		"tsea",
		"ctpa",
		"tctpa",
		"cola1",
		"tcola1",
		"sea1",
		"tsea1",
		"ctpa1",
		"tctpa1",
		"lglholcola",
		"tlglholcola",
		"lglholsea",
		"tlglholsea",
		"lglholctpa",
		"tlglholctpa",
		"minutes",
		"tminutes",
		"hours",
		"thours",
		"hours1",
		"thours1",
		"excess",
		"texcess",
		"ndreg",
		"tndreg",
		"ndot",
		"tndot",
		"dod1",
		"tdod1",
		"dod2",
		"tdod2",
		"dod3",
		"tdod3",
		"dodexcess",
		"tdodexcess",
		"dodndreg",
		"tdodndreg",
		"dodndot",
		"tdodndot",
		"splhol1",
		"tsplhol1",
		"splhol2",
		"tsplhol2",
		"splhol3",
		"tsplhol3",
		"splholexcess",
		"tsplholexcess",
		"splholndreg",
		"tsplholndreg",
		"splholndot",
		"tsplholndot",
		"splholrd1",
		"tsplholrd1",
		"splholrd2",
		"tsplholrd2",
		"splholrd3",
		"tsplholrd3",
		"splholrdexcess",
		"tsplholrdexcess",
		"splholrdndreg",
		"tsplholrdndreg",
		"splholrdndot",
		"tsplholrdndot",
		"lglhol1",
		"tlglhol1",
		"lglhol2",
		"tlglhol2",
		"lglhol3",
		"tlglhol3",
		"lglhol4",
		"tlglhol4",
		"lglholexcess",
		"tlglholexcess",
		"lglholndreg",
		"tlglholndreg",
		"lglholndot",
		"tlglholndot",
		"lglholrd1",
		"tlglholrd1",
		"lglholrd2",
		"tlglholrd2",
		"lglholrd3",
		"tlglholrd3",
		"lglholrd4",
		"tlglholrd4",
		"lglholrdexcess",
		"tlglholrdexcess",
		"lglholrdndreg",
		"tlglholrdndreg",
		"lglholrdndot",
		"tlglholrdndot",
		"shortallow",
		"tshortallow",
		"monthlyallow",
		"tmonthlyallow",
		"grosspay",
		"sss",
		"philhealth",
		"pagibig",
		"deductions",
		"total"
	};
}
